version: "3.3"
services:
  spring-boot-service1:
    image: spring-boot
    ports:
      - "8085:8085"
  spring-boot-service2:
    image: spring-boot
    ports:
      - "8086:8085"
  spring-boot-service3:
    image: spring-boot
    ports:
      - "8087:8085"
  spring-boot-service4:
    image: spring-boot
    ports:
      - "8088:8085"
  prometheus:
    build: './prometheus'
    container_name: 'prometheus'
    ports:
      - "9090:9090"
  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - 3000:3000


