{
 "title": "Prometeus local stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Status code distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(HelloController_hello_request_seconds_count) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Calls by Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(HelloController_hello_request_seconds_count) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}